-- One row per question a member actually asks, traced from the words they type
-- back to the person who types the answer.
--
-- WHY A THIRD LIBRARY
-- /scenarios covers what Evelyn RECOGNISES. /library (db/032) covers what she
-- DOES about it and names the source in prose. /knowledge (db/033) covers the
-- documents and feeds behind those sources. This is the short version of all
-- three, joined up for one question at a time:
--
--   question -> how she decides -> what she reads -> how THAT got filled -> who types it
--
-- It exists because the three libraries each answer one link of that chain, and
-- nobody outside the team wants to read three pages to follow one question.
--
-- WHY THE ROWS ARE NOT SEEDED HERE
-- Unlike db/032 and db/033, whose rows are hand-written prose, these rows are
-- GENERATED from real member messages by tools/questions/build.js and written
-- by tools/questions/seed.js. Hardcoding them in a migration would freeze the
-- example quotes and the counts at the day it was written, and both are meant
-- to be refreshed. Change a question by editing its definition in build.js and
-- re-running; editing a row by hand is overwritten on the next run.
--
-- THE COUNTS ARE A FLOOR, NOT A MEASUREMENT
-- The matcher in build.js is OURS. Unlike tools/scenarios/patterns.js it was
-- not copied out of a live n8n node, so it says nothing about how the bot
-- classified anything — only that a member wrote something matching. It is
-- written narrow on purpose, so every number under-claims. Under-claiming beats
-- a number a Member Care agent can disprove with one counter-example.
--
-- THE EXAMPLES ARE REAL MEMBER MESSAGES
-- Masked before they are stored: e-mail addresses, phone numbers, IBANs and
-- runs of 7+ digits, using the same rules as the scenario-library PDF. Members
-- paste all four straight into the chat and it can turn up in any quote.
--
-- SCOPE: TrainMore.

create table if not exists bot.question_traces (
  key              text primary key,
  sort_order       integer not null default 100,
  brand            text not null default 'trainmore',
  question         text not null,
  examples         text[] not null default '{}',
  matched_messages integer,
  matched_sessions integer,
  -- The window the counts describe, taken from the message cache rather than
  -- assumed, so a page can state it instead of implying "recently".
  window_from      date,
  window_to        date,
  -- Which of the seven routes this answer travels. Denormalised deliberately:
  -- the chains live in build.js next to the questions that use them, and a
  -- lookup table would put half the explanation somewhere else.
  chain_key        text not null,
  chain_label      text not null,
  decides          text not null,
  reads            text not null,
  chain_steps      text[] not null default '{}',
  ends_at          text not null,
  change_cost      text not null,
  caveat           text,
  verified_at      date not null default current_date,
  constraint question_traces_cost_ck check (change_cost in ('nodeploy','deploy','external'))
);

comment on table bot.question_traces is
  'One row per question a member actually asks: how Evelyn decides to answer it, what she reads, and how that source got populated - back to the person who types it. Rows are GENERATED by tools/questions/build.js + seed.js from real member messages, not hand-written, so re-run those rather than editing rows by hand.';
comment on column bot.question_traces.matched_messages is
  'A FLOOR, not a count. The matcher is ours, not the bot own recogniser, and is written narrow so it under-claims.';
comment on column bot.question_traces.examples is
  'Real member messages, masked: e-mail addresses, phone numbers, IBANs and long digit runs are replaced before storage.';

-- The per-chain question count is computed rather than stored, so "how much of
-- the demand does this one source carry" cannot drift out of step with the rows.
create or replace function bot.question_traces_view()
returns table (
  key text, sort_order integer, question text, examples text[],
  matched_messages integer, matched_sessions integer,
  window_from date, window_to date,
  chain_key text, chain_label text, decides text, reads text,
  chain_steps text[], ends_at text, change_cost text, caveat text,
  verified_at date, chain_question_count bigint
)
language sql
stable
as $function$
  select q.key, q.sort_order, q.question, q.examples,
         q.matched_messages, q.matched_sessions, q.window_from, q.window_to,
         q.chain_key, q.chain_label, q.decides, q.reads, q.chain_steps,
         q.ends_at, q.change_cost, q.caveat, q.verified_at,
         count(*) over (partition by q.chain_key)
  from bot.question_traces q
  order by q.sort_order, q.key;
$function$;

comment on function bot.question_traces_view is
  'The traces with a per-chain question count joined on, so a page can show how much of the demand each of the seven sources carries.';

-- Seed:  node tools/questions/build.js && node tools/questions/seed.js
