-- What members ask that Evelyn has no solid answer for.
--
-- The mirror image of bot.knowledge_items. That table is what she KNOWS; this
-- is what she is asked and cannot answer. Both are needed to read either: an
-- article with no demand behind it is a candidate for retirement, and a
-- subject with demand and no article is the work.
--
-- HOW THE SUBJECTS WERE FOUND
-- Not by keyword. Every session in the window where the scorecard says the bot
-- gave NO substantive answer (514 of 9,692, 5.3%) had its member question read
-- by a model, labelled with a subject, and classified as a knowledge gap, an
-- account action, a complaint, or unclear. Only the 44 knowledge ones survive
-- into these rows, merged into 20 canonical subjects.
--
-- THE 44 IS THE HEADLINE FINDING, NOT A LIMITATION
-- 297 of those 437 questions — 68% — were members asking for something to be
-- DONE, not explained: cancel this, change my club, fix my payment. No article
-- would have helped any of them. The gaps below are the remaining 10%. Anyone
-- reading this table as "the reason the bot fails" has the proportions wrong,
-- which is why pool_size and the split are stored per row and shown on the page.
--
-- HOW THE COUNTS WERE MADE, AND WHY NOT BY KEYWORD
-- Two keyword attempts failed in opposite directions. The first required one
-- matching term and credited "Membership prices" with 822 sessions on the
-- strength of `red` and `label` — including a member asking to move clubs. The
-- second required a concept term AND a qualifier term and was measured at 25%
-- RECALL AGAINST ITS OWN SOURCE QUESTIONS: three quarters of the matchers could
-- not find the messages that produced them, so a zero meant a broken matcher
-- rather than an absence. A keyword rule cannot reproduce a judgement made by
-- reading.
--
-- So the counts come from a model reading all 8,232 member questions in the
-- window and assigning each to at most one of these subjects. That method was
-- put through the same recall test and scored 89% (39/44). Both the method and
-- its recall are stored on every row, because a count whose instrument is
-- hidden is exactly what this codebase keeps getting caught by.
--
-- ROWS ARE GENERATED, NOTES ARE NOT
-- tools/gaps/build.js discovers, tools/gaps/count.js counts, seed.js replaces
-- all rows. Notes live in bot.knowledge_item_notes under an `item_key` of
-- `gap:<subject>` — the same soft-keyed table the knowledge items use, which
-- already survives a delete-all refresh and needs no second implementation.
--
-- SCOPE: TrainMore.

create table if not exists bot.knowledge_gaps (
  key            text primary key,
  sort_order     integer not null default 100,
  brand          text not null default 'trainmore',

  subject        text not null,
  question       text not null,
  why_it_matters text not null,
  -- Every raw label folded into this subject. Kept so a reader can see what
  -- was merged and object to a merge they disagree with.
  merged_from    text[] not null default '{}',

  -- How many sessions in the window raised it, and how many of those got no
  -- substantive answer at all. The second is the one that makes it urgent.
  matched_sessions    integer not null default 0,
  unanswered_sessions integer not null default 0,

  -- The instrument, on the row. Never a bare number.
  count_method   text not null,
  count_model    text,
  count_recall_pct integer,
  sessions_read  integer,

  -- Which knowledge items, if any, touch this subject. Empty is the finding.
  covering_item_keys   text[] not null default '{}',
  covering_item_titles text[] not null default '{}',

  examples         text[] not null default '{}',
  example_sessions text[] not null default '{}',

  window_from    date,
  window_to      date,
  -- The no-answer pool these subjects were discovered from, so the page can
  -- state what fraction of the problem this table represents.
  pool_size      integer,
  verified_at    date not null default current_date,

  constraint knowledge_gaps_examples_ck
    check (cardinality(examples) = cardinality(example_sessions))
);

create index if not exists knowledge_gaps_demand_idx
  on bot.knowledge_gaps (unanswered_sessions desc, matched_sessions desc);

comment on table bot.knowledge_gaps is
  'Subjects members raise that no knowledge item answers. Discovered by a model reading the questions from sessions the scorecard marks no_answer; counted by a model reading all member questions in the window. Counts are NOT keyword-derived — two keyword attempts failed at 10x over and 25% recall respectively. Rows are GENERATED by tools/gaps/build.js + count.js + seed.js.';
comment on column bot.knowledge_gaps.count_method is
  'How the number was arrived at. Required: this table exists partly because two earlier counting methods were wrong in opposite directions, and a count without its instrument cannot be argued with.';
comment on column bot.knowledge_gaps.count_recall_pct is
  'Share of the subject''s own source questions the counting pass put back into it. 89% at last run; the keyword matcher it replaced managed 25%. A low value here invalidates the counts.';
comment on column bot.knowledge_gaps.covering_item_keys is
  'Knowledge items that touch this subject, judged on a deliberately LOW bar so that an empty array is a strong claim rather than an artefact of strict matching.';
comment on column bot.knowledge_gaps.pool_size is
  'Sessions with no substantive answer that the subjects were discovered from. 68% of those were account actions, not knowledge gaps; this table covers the other 10%.';

create or replace function bot.knowledge_gaps_view()
returns table (
  key text, sort_order integer, brand text,
  subject text, question text, why_it_matters text, merged_from text[],
  matched_sessions integer, unanswered_sessions integer,
  count_method text, count_model text, count_recall_pct integer, sessions_read integer,
  covering_item_keys text[], covering_item_titles text[],
  examples text[], example_sessions text[],
  window_from date, window_to date, pool_size integer, verified_at date,
  open_notes bigint
)
language sql
stable
as $function$
  select g.key, g.sort_order, g.brand,
         g.subject, g.question, g.why_it_matters, g.merged_from,
         g.matched_sessions, g.unanswered_sessions,
         g.count_method, g.count_model, g.count_recall_pct, g.sessions_read,
         g.covering_item_keys, g.covering_item_titles,
         g.examples, g.example_sessions,
         g.window_from, g.window_to, g.pool_size, g.verified_at,
         coalesce(n.open_notes, 0)
  from bot.knowledge_gaps g
  -- Notes are shared with bot.knowledge_items rather than duplicated: the key
  -- is soft there too, so one table serves both without a second migration.
  left join lateral (
    select count(*) filter (where resolved_at is null) as open_notes
    from bot.knowledge_item_notes nn
    where nn.item_key = g.key
  ) n on true
  order by g.unanswered_sessions desc, g.matched_sessions desc, g.key;
$function$;

comment on function bot.knowledge_gaps_view is
  'The gaps, most-failed first, with open note counts joined from bot.knowledge_item_notes.';

alter table bot.knowledge_gaps enable row level security;

-- Re-seed:  node tools/gaps/build.js && node tools/gaps/count.js && node tools/gaps/seed.js
