// Renders docs/knowledge-sources.md from bot.knowledge_sources.
//
// The document is GENERATED, not written, for the same reason the register is a
// table and not a markdown file: a hand-written copy is accurate on the day it
// is written and wrong a fortnight later, with no signal that it has drifted.
// Re-run this after correcting a row and the document catches up.
//
//   node tools/knowledge/doc.js
//
// /knowledge needs a login; Esther, Nelly and Lowri read things in Teams and
// e-mail. Same content, portable — the same split /scenarios already makes.
const fs = require('fs');
const https = require('https');

const env = {};
for (const line of fs.readFileSync(__dirname + '/../../.env.local', 'utf8').split('\n')) {
  const t = line.trim();
  if (t.includes('=') && !t.startsWith('#')) {
    const i = t.indexOf('=');
    env[t.slice(0, i)] = t.slice(i + 1).replace(/^["']|["']$/g, '');
  }
}
const SUPA = env.SUPABASE_URL.replace(/\/$/, '');
const KEY = env.SUPABASE_SERVICE_ROLE_KEY;

function rpc(name) {
  return new Promise((res, rej) => {
    const body = JSON.stringify({});
    const r = https.request(SUPA + '/rest/v1/rpc/' + name, {
      method: 'POST',
      headers: {
        apikey: KEY, Authorization: 'Bearer ' + KEY,
        'Content-Profile': 'bot', 'Accept-Profile': 'bot',
        'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body),
      },
    }, (r2) => {
      let b = '';
      r2.on('data', (d) => b += d);
      r2.on('end', () => { try { res(JSON.parse(b)); } catch (e) { rej(new Error(b.slice(0, 300))); } });
    });
    r.on('error', rej);
    r.write(body);
    r.end();
  });
}

const WIRING = {
  live: {
    label: 'Live',
    what: 'Re-read automatically. Change the source and the bot follows, with no deploy.',
  },
  deploy: {
    label: 'Needs a deploy',
    what: 'Written into an n8n node. Changing it needs an edit and a publish.',
  },
  not_wired: {
    label: 'Not wired',
    what: 'Nothing reads this. Editing it changes nothing until someone copies it across by hand.',
  },
};
const ORDER = ['live', 'deploy', 'not_wired'];

const fmt = (d) => d
  ? new Date(d + 'T00:00:00Z').toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' })
  : null;

(async () => {
  const rows = await rpc('knowledge_sources_view');
  if (!Array.isArray(rows)) throw new Error('unexpected response: ' + JSON.stringify(rows).slice(0, 200));

  const oldest = rows.reduce((a, r) => (a === null || r.verified_at < a ? r.verified_at : a), null);
  const notWired = rows.filter((r) => r.wiring === 'not_wired');
  const risks = rows.filter((r) => r.risk);

  const out = [];
  out.push('# What is influencing Evelyn\'s knowledge');
  out.push('');
  out.push('*Generated from `bot.knowledge_sources` by `tools/knowledge/doc.js`. Do not edit this file &mdash;');
  out.push('correct the table with an `UPDATE` and re-run, which needs no deploy.*');
  out.push('');
  out.push(`**${rows.length} sources · ${notWired.length} not wired · ${risks.length} carrying a warning · oldest check ${fmt(oldest)}**`);
  out.push('');
  out.push('Every document and feed that shapes what the bot knows, including the ones that produced no FAQ at');
  out.push('all. TrainMore.');
  out.push('');
  out.push('## There is no ingestion log');
  out.push('');
  out.push('The FAQ store is rebuilt from scratch every morning, so every row in it carries today\'s date and the');
  out.push('store remembers nothing about when a document first arrived or last changed anything. Every date');
  out.push('below is therefore **reconstructed**, and each entry records from what &mdash; a file\'s own modified');
  out.push('date, a date built into an n8n node name, or a commit.');
  out.push('');
  out.push('The real fix is for the daily sync to write a row each time it imports something: what, from where,');
  out.push('how many chunks, when. Then this register is generated rather than curated. Until that exists, this');
  out.push('is the record.');
  out.push('');
  out.push('## At a glance');
  out.push('');
  out.push('| Source | Wiring | FAQs | Last used |');
  out.push('|---|---|---|---|');
  for (const r of rows) {
    out.push(`| ${r.name} | ${WIRING[r.wiring].label} | ${r.faq_count != null ? r.faq_count : '&mdash;'} | ${fmt(r.last_used_at) || 'continuous'} |`);
  }
  out.push('');

  for (const w of ORDER) {
    const group = rows.filter((r) => r.wiring === w);
    if (!group.length) continue;
    out.push(`## ${WIRING[w].label}`);
    out.push('');
    out.push(`*${WIRING[w].what}*`);
    out.push('');
    for (const r of group) {
      out.push(`### ${r.name}`);
      out.push('');
      out.push(`*${r.kind}${r.faq_count != null ? ` · ${r.faq_count} FAQs` : ''} · checked ${fmt(r.verified_at)}*`);
      out.push('');
      out.push(`- **Last used.** ${r.last_used}`);
      out.push(`- **How we know.** ${r.evidence}`);
      out.push(`- **What it shapes.** ${r.influences}`);
      out.push(`- **Who owns it.** ${r.owner}`);
      if (r.url) out.push(`- **Open it.** ${r.url}`);
      if (r.risk) {
        out.push('');
        out.push(`> **Watch out.** ${r.risk}`);
      }
      out.push('');
    }
  }

  const path = __dirname + '/../../docs/knowledge-sources.md';
  fs.writeFileSync(path, out.join('\n'));
  console.log('wrote docs/knowledge-sources.md —', rows.length, 'sources,', notWired.length, 'not wired');
})().catch((e) => { console.error('FAILED:', e.message); process.exit(1); });
